# docker-build:
#   # Official docker image.
#   image: docker:latest
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
#     - docker push "$CI_REGISTRY_IMAGE"
#   variables:
#     DOCKER_HOST: tcp://localhost:2375
#     DOCKER_TLS_CERTDIR: ""

# deploy:
#   stage: deploy
#   image: 
#     name: bitnami/kubectl
#     entrypoint: [""]  
#   script:
#     - kubectl get deployment demo-golang-docker || kubectl create deployment demo-golang-docker --image="$CI_REGISTRY_IMAGE":0.0.2.SNAPSHOT
#     - kubectl set image deployment/demo-golang-docker demo-golang-docker="$CI_REGISTRY_IMAGE":0.0.2.SNAPSHOT

deploy_review:
    stage: deploy
    image: devth/helm
    script:
        - helm version
        - helm init
        - helm upgrade
          --install
          --wait
          --force
          demo-golang-docker
          ./charts