image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker info
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - kubectl get deployment demo-golang-docker || kubectl create deployment demo-golang-docker --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    - kubectl set image deployment/demo-golang-docker demo-golang-docker="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"