language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pablon27/demo-golang-docker .

script:
  - docker run -e CI=true pablon27/demo-golang-docker golangci-lint run go test -v -race ./test 
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-514473135315"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY